name: GUI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  gui-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qt5-default \
          qtbase5-dev \
          qttools5-dev \
          libgl1-mesa-dev \
          xvfb \
          x11-utils
    
    - name: Setup virtual display
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        
    - name: Build GUI components
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_GUI_TESTS=ON
        cmake --build build --parallel $(nproc)
        
    - name: Run GUI tests
      env:
        DISPLAY: :99
      run: |
        cd build
        ./gui_tests || true
        
    - name: Capture GUI test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: gui-test-results
        path: build/test-results/
        retention-days: 3
